/** All static user-facing strings live here so the guardrail test can scan them. */
export const copy = {
  brand: 'Second Look',
  disclaimer: 'This is information, not investment advice.',
  landing: {
    eyebrow: 'SIP pause or reduction',
    cta: 'Try the Second Look',
    tagline: 'Platforms already make pausing easy. Second Look makes it informed.',
    arjunTitle: 'Same button, different need',
    arjunBody: 'Arjun, 34, needs ₹40,000 for a medical bill. Try his pause.',
    arjunCta: "Try Arjun's pause",
  },
  sip: {
    title: 'My SIPs',
    pause: 'Pause',
    stop: 'Stop',
    resume: 'Resume SIP',
    reset: 'Restart demo',
    stopTitle: 'Stop is outside this prototype',
    stopBody: "Second Look's MVP covers Pause or reduce. Stop isn't part of this demo.",
    close: 'Close',
  },
  reason: {
    title: "What's making you pause?",
    sub: 'One tap. You can still pause right after.',
    market: 'Market is falling',
    cash: 'Need cash',
    just: 'Just pause',
    fund: "Fund isn't performing",
    marketHint: 'See what pausing changes for your goal',
    cashHint: 'Quick ways to free up money',
    justHint: 'Skip straight to your choice',
    v2Title: 'Coming in V2',
    v2Body: 'This path is not part of the MVP.',
    v2Preview: 'Future version',
    v2Detail:
      'Compare 3y and 5y rolling returns vs category median, expense ratio, fund overlap and alternative SIP routing.',
    v2Back: 'Back to reasons',
  },
  fear: {
    title: 'Before you pause',
    goal: 'GOAL IMPACT',
    price: 'PRICE TODAY',
    past: 'PAST FALLS',
    priceLine: (pct: number, amount: string) => `At today's prices, ${amount} buys ${pct}% more units than in July.`,
    pastLine: 'Flexi-cap funds have experienced similar drawdowns before.',
    illustrative: 'Illustrative historical range; varies by drawdown and fund.',
    why: 'Why am I seeing this?',
    options: 'See my options',
    pauseAnyway: 'Pause anyway',
    keep: 'Keep going',
    pause: (m: number) => `Pause ${m} months`,
    barCaption: 'Projected value at the end of the period, relative to keeping your SIP running. A scenario comparison.',
    footerNote: 'You can still pause at any time.',
  },
  why: {
    title: 'Why am I seeing this?',
    data: 'Data',
    assumptions: 'Assumptions',
    updated: 'Updated',
    engineNote:
      'Numbers come from a fixed calculation, not from AI. The wording is generated from those numbers and checked for advice language.',
    how: 'How each number was calculated',
    consent: 'Your authorised portfolio data is used only for this decision.',
    close: 'Close',
  },
  decision: {
    title: 'Your choice',
    sub: 'All of these are yours to pick.',
    continue: 'Continue',
    continueSub: (amount: string) => `Keeps your ${amount} SIP running`,
    pause1: 'Pause 1 month',
    pause1Sub: (skip: string, resume: string) => `Skips ${skip}, resumes ${resume}`,
    remind: 'Remind me in 48 hours',
    remindSub: (date: string) => `Nothing changes now. We'll ask again on ${date}`,
    pauseAnyway: 'Pause anyway',
    pauseAnywaySub: (resume: string) => `Pauses for 6 months, resumes ${resume}`,
    footer: 'You can still pause at any time.',
  },
  cash: {
    title: 'Need cash?',
    body: 'Your SIP is one of several places you can create short-term cash flexibility.',
    pause: 'Pause SIP',
    pauseNote: 'Pauses for 6 months. You can resume any time.',
    skip: 'Skip 1 instalment',
    reduce: 'Reduce amount',
    move: 'Move SIP date',
    emergency: 'Emergency-fund check',
    skipSub: (skip: string, resume: string) => `Skip ${skip}, continue ${resume}`,
    reduceSub: 'Keep investing a smaller amount',
    moveSub: 'Shift the instalment to a day that suits you',
    emergencySub: 'What pausing does and does not free up',
    reduceTitle: 'Reduce amount',
    reduceSheetSub: 'Pick a monthly amount',
    reduceConfirm: 'Confirm reduction',
    moveTitle: 'Move SIP date',
    moveSheetSub: 'Pick a new day of the month',
    moveConfirm: 'Confirm new date',
    emergencyTitle: 'Emergency-fund check',
    emergencyLines: [
      "Pausing stops future instalments. It doesn't release money already invested.",
      'While paused, your monthly instalment amount stays in your bank account.',
      'Skipping one instalment frees up one month of your SIP amount.',
    ],
  },
  confirm: {
    title: 'Confirmed',
    saved: 'Choice saved',
    checkinTitle: 'Check-in on day 30',
    checkinBody: "We'll check in again after 30 days.",
    done: 'Done',
    preview: 'Preview day-30 check-in',
  },
  checkin: {
    preview: 'Prototype preview of the day-30 message.',
    back: 'Back to SIP',
    restart: 'Start over',
  },
  panel: {
    title: 'Demo info',
    persona: 'Why this investor pauses',
    says: 'SAYS',
    thinks: 'THINKS',
    pipeline: 'How it works',
    stages: [
      ['Data', 'User-authorised portfolio, goal, NAV'],
      ['Calculation engine', 'Deterministic. Produces every number'],
      ['Reason classifier', 'The chip decides which card appears'],
      ['AI explainer', 'Plain language, advice phrases blocked'],
      ["Investor's screen", 'Pause anyway always visible'],
    ] as [string, string][],
    log: 'Demo event log · this session only',
    logEmpty: 'Events appear here as you click.',
    marketFall: 'Market down ~12%',
  },
} as const
