/** All static user-facing strings live here so the guardrail test can scan them. */
export const copy = {
  brand: 'Second Look',
  disclaimer: 'This is information, not investment advice.',
  account: {
    title: 'Account',
    switch: 'Switch account',
    tips: 'Tips',
    reset: 'Start over',
  },
  sip: {
    title: 'My SIPs',
    pause: 'Pause',
    stop: 'Stop',
    resume: 'Resume SIP',
    stopTitle: 'Stop is outside this prototype',
    stopBody: "Second Look's MVP covers Pause or reduce. Stop isn't part of this demo.",
    close: 'Close',
  },
  reason: {
    title: "What's making you pause?",
    sub: 'One tap. You can still pause right after.',
    market: 'Market is falling',
    cash: 'Need cash',
    just: 'Just pause',
    fund: "Fund isn't performing",
    marketHint: 'See what pausing changes for your goal',
    cashHint: 'Quick ways to free up money',
    justHint: 'Skip straight to your choice',
    v2Title: 'Coming in V2',
    v2Body: 'This path is not part of the MVP.',
    v2Preview: 'Future version',
    v2Detail:
      'Compare 3y and 5y rolling returns vs category median, expense ratio, fund overlap and alternative SIP routing.',
    v2Back: 'Back to reasons',
  },
  fear: {
    title: 'Before you pause',
    goal: 'GOAL IMPACT',
    price: 'PRICE TODAY',
    past: 'PAST FALLS',
    priceLine: (pct: number, amount: string) => `At today's prices, ${amount} buys ${pct}% more units than in July.`,
    pastLine: 'Flexi-cap funds have experienced similar drawdowns before.',
    illustrative: 'Illustrative historical range; varies by drawdown and fund.',
    why: 'Why am I seeing this?',
    options: 'See my options',
    pauseAnyway: 'Pause anyway',
    keep: 'Keep going',
    pause: (m: number) => `Pause ${m} months`,
    barCaption: 'Projected value at the end of the period, relative to keeping your SIP running. A scenario comparison.',
    footerNote: 'You can still pause at any time.',
  },
  why: {
    title: 'Why am I seeing this?',
    data: 'Data',
    assumptions: 'Assumptions',
    updated: 'Updated',
    engineNote:
      'Numbers come from a fixed calculation, not from AI. The wording is generated from those numbers and checked for advice language.',
    how: 'How each number was calculated',
    consent: 'Your authorised portfolio data is used only for this decision.',
    close: 'Close',
  },
  decision: {
    title: 'Your choice',
    sub: 'All of these are yours to pick.',
    continue: 'Continue',
    continueSub: (amount: string) => `Keeps your ${amount} SIP running`,
    pause1: 'Pause 1 month',
    pause1Sub: (skip: string, resume: string) => `Skips ${skip}, resumes ${resume}`,
    remind: 'Remind me in 48 hours',
    remindSub: (date: string) => `Nothing changes now. We'll ask again on ${date}`,
    pauseAnyway: 'Pause anyway',
    pauseAnywaySub: (resume: string) => `Pauses for 6 months, resumes ${resume}`,
    footer: 'You can still pause at any time.',
  },
  cash: {
    title: 'Need cash?',
    body: 'Your SIP is one of several places you can create short-term cash flexibility.',
    pause: 'Pause SIP',
    pauseNote: 'Pauses for 6 months. You can resume any time.',
    skip: 'Skip 1 instalment',
    reduce: 'Reduce amount',
    move: 'Move SIP date',
    emergency: 'Emergency-fund check',
    skipSub: (skip: string, resume: string) => `Skip ${skip}, continue ${resume}`,
    reduceSub: 'Keep investing a smaller amount',
    moveSub: 'Shift the instalment to a day that suits you',
    emergencySub: 'What pausing does and does not free up',
    reduceTitle: 'Reduce amount',
    reduceSheetSub: 'Pick a monthly amount',
    reduceConfirm: 'Confirm reduction',
    moveTitle: 'Move SIP date',
    moveSheetSub: 'Pick a new day of the month',
    moveConfirm: 'Confirm new date',
    emergencyTitle: 'Emergency-fund check',
    emergencyLines: [
      "Pausing stops future instalments. It doesn't release money already invested.",
      'While paused, your monthly instalment amount stays in your bank account.',
      'Skipping one instalment frees up one month of your SIP amount.',
    ],
  },
  confirm: {
    title: 'Confirmed',
    saved: 'Choice saved',
    checkinTitle: 'Check-in on day 30',
    checkinBody: "We'll check in again after 30 days.",
    done: 'Done',
    preview: 'See day-30 check-in',
  },
  checkin: {
    preview: '30 days later',
    back: 'Back to SIP',
    restart: 'Start over',
  },
  tour: {
    skip: 'Skip tips',
    next: 'Next',
    gotIt: 'Got it',
    tips: {
      sip_detail: [
        { target: 'pause', title: 'Tap Pause', body: 'See what Second Look shows before the pause is final.' },
        { target: 'sip-card', title: 'Your SIP at a glance', body: 'Amount, next instalment, performance and progress toward your goal.' },
        { target: 'portfolio', title: 'Why people pause', body: 'A falling portfolio is when many investors reach for Pause.' },
        { target: 'avatar', title: 'Switch investor', body: "Open the account menu to try Arjun's cash-need path." },
      ],
      reason: [
        { target: 'reason-market_falling', title: 'Market is falling', body: 'Opens a card built from your goal, SIP and portfolio.' },
        { target: 'reason-need_cash', title: 'Need cash', body: 'No lecture: Pause comes first, plus ways to free up cash.' },
        { target: 'reason-just_pause', title: 'Just pause', body: 'Goes straight to your choice with no extra steps.' },
        { target: 'reason-fund_doubt', title: 'Coming in V2', body: 'Fund comparison is not part of this version.' },
      ],
      fear: [
        { target: 'goal-card', title: 'What a pause changes', body: 'A 6-month pause compared with keeping your SIP running.' },
        { target: 'price-card', title: "Today's price level", body: 'A fact about the current price, not a prediction.' },
        { target: 'past-card', title: 'Past falls', body: 'Illustrative recovery times, including the slow cases.' },
        { target: 'why', title: 'Where the numbers come from', body: 'Sources, assumptions and the update date for every figure.' },
        { target: 'options', title: 'See your options', body: 'Continue, pause for a month, get a reminder, or pause.' },
        { target: 'pause-anyway', title: 'Still your call', body: 'Pause anyway is always one tap.' },
      ],
      why: [
        { target: 'why-plain', title: 'In plain words', body: 'A short summary written from the calculated numbers.' },
        { target: 'why-assumptions', title: 'Sources and assumptions', body: 'What the numbers are based on and when they were updated.' },
        { target: 'why-how', title: 'Check the maths', body: 'Each figure with its inputs and calculation.' },
      ],
      decision: [
        { target: 'decision-list', title: 'Your choice', body: 'All options carry equal weight. Nothing is pre-selected.' },
        { target: 'choice-remind_48h', title: '48-hour reminder', body: 'Nothing changes now. You decide again in two days.' },
        { target: 'choice-pause_anyway', title: 'Pause anyway', body: 'Always available, whatever you read before.' },
      ],
      cash: [
        { target: 'cash-pause', title: 'Pause comes first', body: 'No lecture for a cash need.' },
        { target: 'cash-skip', title: 'Skip one instalment', body: 'Frees up one month and keeps your SIP in place.' },
        { target: 'cash-reduce', title: 'Reduce the amount', body: 'Invest less each month instead of stopping.' },
        { target: 'cash-emergency', title: 'Emergency-fund check', body: 'What pausing does and does not free up.' },
      ],
      confirmed: [
        { target: 'outcome', title: 'All set', body: 'Your choice is saved.' },
        { target: 'checkin-card', title: 'Day-30 check-in', body: "We'll ask how it's going after 30 days." },
        { target: 'confirm-preview', title: 'See it now', body: 'Preview the day-30 check-in.' },
      ],
      checkin: [{ target: 'checkin-card', title: 'One month later', body: 'How your choice looks after 30 days.' }],
    } as Record<string, { target: string; title: string; body: string }[]>,
  },
  panel: {
    title: 'Demo info',
    persona: 'Why this investor pauses',
    says: 'SAYS',
    thinks: 'THINKS',
    pipeline: 'How it works',
    stages: [
      ['Data', 'User-authorised portfolio, goal, NAV'],
      ['Calculation engine', 'Deterministic. Produces every number'],
      ['Reason classifier', 'The chip decides which card appears'],
      ['AI explainer', 'Plain language, advice phrases blocked'],
      ["Investor's screen", 'Pause anyway always visible'],
    ] as [string, string][],
    log: 'Demo event log · this session only',
    logEmpty: 'Events appear here as you click.',
    marketFall: 'Market down ~12%',
  },
} as const
